### ISSUE TITLE
concurrently: command not found when running yarn create

### ISSUE THREAD

**Issue by the-vampiire** [adriandelgg/ts-next-hardhat-template#4]
```sh
yarn create ether-dapp my-dapp 
```

output

```sh
Output:
/bin/sh: concurrently: command not found
```

**Comment by adriandelgg** [comment]
> ```shell
> yarn create ether-dapp my-dapp 
> ```
> 
> output
> 
> ```shell
> Output:
> /bin/sh: concurrently: command not found
> ```

Make sure to install dependencies at the root of the project.
